zuul:
  prefix: /api
  routes:
    person-user-profile-api:
      path: /person/**
      uri: https://person-profile-api.herokuapp.com/
    person-client-api:
      path: /client/**
      uri: https://person-client-api.herokuapp.com/

 zuul:
  routes:
    first:
      path: /first/**
      url: https://first.example.com
    second:
      path: /second/**
      url: forward:/second
    third:
      path: /third/**
      url: forward:/3rd
    legacy:
      path: /**
      url: https://legacy.example.com

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://service-registry-person.herokuapp.com/eureka/
  instance:
    hostname: service-registry-person.herokuapp.com

server:
  port: 8074

spring:
  application:
    name: zuul-proxy-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000